### ISSUE TITLE
hashcat-utils/bin/splitlen.app: 1: hashcat-utils/bin/splitlen.app: ����: not found

### ISSUE THREAD

**Issue by Bal33p** [trustedsec/hate_crack#13]
Hello,
I am following your guide on the TrestedSec release site and have created my wordlists file exactly as you have specified. When i run the following command i am getting this error... any thoughts on this one. 

PC is a new ubuntu 16.04LTS build dual NVIDIA GTX 1080 FE's 
Hashcat installed from PTF and hate_crack installed in home directory. 
 

Thanks for the great tool! I got it running on my MAC and it is great! 

:~/hate_crack$ python wordlist_optimizer.py wordlists.txt ../optimized_wordlists/
/home/redacted/Passwords/wordlists/hashes.org-2017.txt
hashcat-utils/bin/splitlen.app: 1: hashcat-utils/bin/splitlen.app: ����: not found
hashcat-utils/bin/splitlen.app: 2: hashcat-utils/bin/splitlen.app: Syntax error: word unexpected (expecting ")")

**Comment by bandrel** [comment]
the splitlen.app is for OXS only.  I'll modify the script to detect if you are using osx or linux and use the appropriate binary.

In the meantime you should be able to modify https://github.com/trustedsec/hate_crack/blob/5810130a22e49224a4f80a2503f60d90c4744dd4/wordlist_optimizer.py#L8-L9
with splitlen.bin instead of splitlen.app

**Comment by Bal33p** [comment]
That did it!  You are the man!! 
Thanks!
